namespace EmvCardReader.Emv;

/// <summary>Dictionary of EMV / BER-TLV tags -> human readable names.</summary>
public static class EmvTags
{
    public static string Name(string tag)
        => Map.TryGetValue(tag.ToUpperInvariant(), out var n) ? n : "Unknown";

    public static bool IsKnown(string tag) => Map.ContainsKey(tag.ToUpperInvariant());

    public static readonly IReadOnlyDictionary<string, string> Map = new Dictionary<string, string>
    {
        // ---- Templates / structural ----
        ["6F"] = "FCI Template",
        ["A5"] = "FCI Proprietary Template",
        ["BF0C"] = "FCI Issuer Discretionary Data",
        ["61"] = "Application Template (Directory Entry)",
        ["70"] = "Record Template / READ RECORD Response",
        ["71"] = "Issuer Script Template 1",
        ["72"] = "Issuer Script Template 2",
        ["73"] = "Directory Discretionary Template",
        ["77"] = "Response Message Template Format 2",
        ["80"] = "Response Message Template Format 1",
        ["88"] = "Short File Identifier (SFI)",

        // ---- Card / application identification ----
        ["4F"] = "Application Identifier (AID) - card",
        ["50"] = "Application Label",
        ["84"] = "Dedicated File (DF) Name",
        ["87"] = "Application Priority Indicator",
        ["9F38"] = "Processing Options Data Object List (PDOL)",
        ["9F11"] = "Issuer Code Table Index",
        ["9F12"] = "Application Preferred Name",
        ["5F2D"] = "Language Preference",
        ["5F50"] = "Issuer URL",

        // ---- Cardholder / account ----
        ["5A"] = "Application PAN (Card Number)",
        ["5F20"] = "Cardholder Name",
        ["5F24"] = "Application Expiration Date (YYMMDD)",
        ["5F25"] = "Application Effective Date (YYMMDD)",
        ["5F28"] = "Issuer Country Code",
        ["5F2A"] = "Transaction Currency Code",
        ["5F30"] = "Service Code",
        ["5F34"] = "Application PAN Sequence Number",
        ["5F36"] = "Transaction Currency Exponent",
        ["57"] = "Track 2 Equivalent Data",
        ["56"] = "Track 1 Equivalent Data",
        ["9F1F"] = "Track 1 Discretionary Data",
        ["9F20"] = "Track 2 Discretionary Data",

        // ---- Processing / risk management ----
        ["82"] = "Application Interchange Profile (AIP)",
        ["94"] = "Application File Locator (AFL)",
        ["8C"] = "Card Risk Management DOL 1 (CDOL1)",
        ["8D"] = "Card Risk Management DOL 2 (CDOL2)",
        ["8E"] = "Cardholder Verification Method (CVM) List",
        ["8F"] = "Certification Authority Public Key Index",
        ["90"] = "Issuer Public Key Certificate",
        ["92"] = "Issuer Public Key Remainder",
        ["93"] = "Signed Static Application Data",
        ["95"] = "Terminal Verification Results (TVR)",
        ["97"] = "Transaction Certificate DOL (TDOL)",
        ["9A"] = "Transaction Date",
        ["9B"] = "Transaction Status Information",
        ["9C"] = "Transaction Type",
        ["9D"] = "Directory Definition File (DDF) Name",
        ["83"] = "Command Template",
        ["86"] = "Issuer Script Command",
        ["9F07"] = "Application Usage Control",
        ["9F08"] = "Application Version Number (Card)",
        ["9F09"] = "Application Version Number (Terminal)",
        ["9F0B"] = "Cardholder Name Extended",
        ["9F0D"] = "Issuer Action Code - Default",
        ["9F0E"] = "Issuer Action Code - Denial",
        ["9F0F"] = "Issuer Action Code - Online",
        ["9F10"] = "Issuer Application Data",
        ["9F13"] = "Last Online ATC Register",
        ["9F14"] = "Lower Consecutive Offline Limit",
        ["9F17"] = "PIN Try Counter",
        ["9F23"] = "Upper Consecutive Offline Limit",
        ["9F26"] = "Application Cryptogram",
        ["9F27"] = "Cryptogram Information Data",
        ["9F36"] = "Application Transaction Counter (ATC)",
        ["9F4C"] = "ICC Dynamic Number",
        ["9F4D"] = "Log Entry (SFI + #records)",
        ["9F4F"] = "Log Format",

        // ---- ICC public key (offline data authentication) ----
        ["9F32"] = "Issuer Public Key Exponent",
        ["9F46"] = "ICC Public Key Certificate",
        ["9F47"] = "ICC Public Key Exponent",
        ["9F48"] = "ICC Public Key Remainder",
        ["9F49"] = "Dynamic Data Authentication DOL (DDOL)",
        ["9F4A"] = "Static Data Authentication Tag List",
        ["9F4B"] = "Signed Dynamic Application Data",

        // ---- Terminal / transaction (PDOL, CDOL, logs) ----
        ["9F01"] = "Acquirer Identifier",
        ["9F02"] = "Amount, Authorised (Numeric)",
        ["9F03"] = "Amount, Other (Numeric)",
        ["9F04"] = "Amount, Other (Binary)",
        ["9F05"] = "Application Discretionary Data",
        ["9F06"] = "Application Identifier (AID) - terminal",
        ["9F15"] = "Merchant Category Code",
        ["9F16"] = "Merchant Identifier",
        ["9F18"] = "Issuer Script Identifier",
        ["9F1A"] = "Terminal Country Code",
        ["9F1B"] = "Terminal Floor Limit",
        ["9F1C"] = "Terminal Identification",
        ["9F1D"] = "Terminal Risk Management Data",
        ["9F1E"] = "Interface Device (IFD) Serial Number",
        ["9F21"] = "Transaction Time",
        ["9F33"] = "Terminal Capabilities",
        ["9F34"] = "Cardholder Verification Method (CVM) Results",
        ["9F35"] = "Terminal Type",
        ["9F37"] = "Unpredictable Number",
        ["9F39"] = "Point-of-Service (POS) Entry Mode",
        ["9F40"] = "Additional Terminal Capabilities",
        ["9F41"] = "Transaction Sequence Counter",
        ["9F42"] = "Application Currency Code",
        ["9F43"] = "Application Reference Currency Exponent",
        ["9F44"] = "Application Currency Exponent",
        ["9F45"] = "Data Authentication Code",
        ["9F4E"] = "Merchant Name and Location",
        ["9F50"] = "Offline Accumulator Balance",
        ["9F51"] = "Application Currency Code (Issuer)",
        ["9F52"] = "Application Default Action (ADA)",
        ["9F53"] = "Consecutive Transaction Counter Int. Limit",
        ["9F54"] = "Cumulative Total Tx Amount Limit",
        ["9F55"] = "Geographic Indicator",
        ["9F56"] = "Issuer Authentication Indicator",
        ["9F57"] = "Issuer Country Code",
        ["9F58"] = "Lower Consecutive Offline Limit",
        ["9F59"] = "Upper Consecutive Offline Limit",
        ["9F5A"] = "Application Program ID",
        ["9F5B"] = "Issuer Script Results",
        ["9F5C"] = "Cumulative Total Tx Amount Upper Limit",
        ["9F66"] = "Terminal Transaction Qualifiers (TTQ)",
        ["9F6C"] = "Card Transaction Qualifiers (CTQ)",
        ["9F6E"] = "Form Factor Indicator / Third Party Data",
        ["9F7C"] = "Merchant Custom Data / Customer Exclusive Data",

        // ---- Misc ----
        ["42"] = "Issuer Identification Number (IIN)",
        ["4D"] = "Card Status Update",
        ["DF8104"] = "Balance Read Before Gen AC",
        ["DF8105"] = "Balance Read After Gen AC",
    };
}
